version: "3"

services:
  zkevm-bridge-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: zkevm-bridge-ui
    command: >
      sh -c "git pull && docker compose build "
    container_name: zkevm-bridge-ui
    ports:
      - 8130:80